FROM rustlang/rust:nightly
RUN apt-get -y update && apt-get -y install musl-tools && apt-get -y install curl
RUN rustup target add x86_64-unknown-linux-musl

# Install wasm32-unknown-unknown-target
RUN rustup default nightly
RUN rustup target add wasm32-unknown-unknown \
  x86_64-unknown-linux-musl

# Install WASM pack
RUN curl -L https://github.com/rustwasm/wasm-pack/releases/download/v0.6.0/wasm-pack-v0.6.0-x86_64-unknown-linux-musl.tar.gz | tar --strip-components=1 --wildcards -xzf - "*/wasm-pack" &&\
  chmod +x wasm-pack &&\
  mv wasm-pack /usr/local/bin/

RUN curl -sL https://deb.nodesource.com/setup_10.x | bash - && apt-get install -y nodejs && rm -rf /var/lib/apt/lists/*
WORKDIR '/app'
COPY ./package.json ./
RUN npm install
COPY . .
CMD ["npm", "run", "start"]
